# Transcoder Configuration Gemma Scope Transcoders (3rd lowest L0)
model_name: "google/gemma-2-2b"
feature_input_hook: "ln2.hook_normalized"
feature_output_hook: 'hook_mlp_out'

transcoders:
  - id: "gemma-2-2b-gemmascope-0-l0-165"
    layer: 0
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_0/width_16k/average_l0_165/params.npz"
    
  - id: "gemma-2-2b-gemmascope-1-l0-173"
    layer: 1
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_1/width_16k/average_l0_173/params.npz"
    
  - id: "gemma-2-2b-gemmascope-2-l0-155"
    layer: 2
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_2/width_16k/average_l0_155/params.npz"
    
  - id: "gemma-2-2b-gemmascope-3-l0-167"
    layer: 3
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_3/width_16k/average_l0_167/params.npz"
    
  - id: "gemma-2-2b-gemmascope-4-l0-282"
    layer: 4
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_4/width_16k/average_l0_282/params.npz"
    
  - id: "gemma-2-2b-gemmascope-5-l0-272"
    layer: 5
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_5/width_16k/average_l0_272/params.npz"
    
  - id: "gemma-2-2b-gemmascope-6-l0-329"
    layer: 6
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_6/width_16k/average_l0_329/params.npz"
    
  - id: "gemma-2-2b-gemmascope-7-l0-245"
    layer: 7
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_7/width_16k/average_l0_245/params.npz"
    
  - id: "gemma-2-2b-gemmascope-8-l0-168"
    layer: 8
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_8/width_16k/average_l0_168/params.npz"
    
  - id: "gemma-2-2b-gemmascope-9-l0-235"
    layer: 9
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_9/width_16k/average_l0_235/params.npz"
    
  - id: "gemma-2-2b-gemmascope-10-l0-287"
    layer: 10
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_10/width_16k/average_l0_287/params.npz"
    
  - id: "gemma-2-2b-gemmascope-11-l0-17"
    layer: 11
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_11/width_16k/average_l0_17/params.npz"
    
  - id: "gemma-2-2b-gemmascope-12-l0-18"
    layer: 12
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_12/width_16k/average_l0_18/params.npz"
    
  - id: "gemma-2-2b-gemmascope-13-l0-26"
    layer: 13
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_13/width_16k/average_l0_26/params.npz"
    
  - id: "gemma-2-2b-gemmascope-14-l0-24"
    layer: 14
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_14/width_16k/average_l0_24/params.npz"
    
  - id: "gemma-2-2b-gemmascope-15-l0-25"
    layer: 15
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_15/width_16k/average_l0_25/params.npz"
    
  - id: "gemma-2-2b-gemmascope-16-l0-29"
    layer: 16
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_16/width_16k/average_l0_29/params.npz"
    
  - id: "gemma-2-2b-gemmascope-17-l0-34"
    layer: 17
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_17/width_16k/average_l0_34/params.npz"
    
  - id: "gemma-2-2b-gemmascope-18-l0-34"
    layer: 18
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_18/width_16k/average_l0_34/params.npz"
    
  - id: "gemma-2-2b-gemmascope-19-l0-32"
    layer: 19
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_19/width_16k/average_l0_32/params.npz"
    
  - id: "gemma-2-2b-gemmascope-20-l0-31"
    layer: 20
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_20/width_16k/average_l0_31/params.npz"
    
  - id: "gemma-2-2b-gemmascope-21-l0-36"
    layer: 21
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_21/width_16k/average_l0_36/params.npz"
    
  - id: "gemma-2-2b-gemmascope-22-l0-40"
    layer: 22
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_22/width_16k/average_l0_40/params.npz"
    
  - id: "gemma-2-2b-gemmascope-23-l0-69"
    layer: 23
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_23/width_16k/average_l0_69/params.npz"
    
  - id: "gemma-2-2b-gemmascope-24-l0-96"
    layer: 24
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_24/width_16k/average_l0_96/params.npz"
    
  - id: "gemma-2-2b-gemmascope-25-l0-110"
    layer: 25
    filepath: "hf://google/gemma-scope-2b-pt-transcoders/layer_25/width_16k/average_l0_110/params.npz"
    